version: "3.9"
   
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  backend:
    build:
      context: ./Backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    depends_on:
      - redis