version: "3.9"
   
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  backend:
    build:
      context: ./Backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    depends_on:
      - redis