# Generated by Django 3.2.12 on 2023-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_file',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_raw',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
